{
 "title": "Stock-Dashboard",
 "time": { "from": "2024-03-05T14:26:00.000Z", "to": "2024-03-05T20:56:00.000Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Stock-Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AAPL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "SELECT stock, utc_timestamp, curr_price\nFROM stock.stock_table\nWHERE stock = 'AAPL'\nORDER BY utc_timestamp ASC;"
    }
   ]
  },
  {
   "title": "MSFT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "target": "SELECT stock, utc_timestamp, curr_price\nFROM stock.stock_table\nWHERE stock = 'MSFT'\nORDER BY utc_timestamp ASC;"
    }
   ]
  },
  {
   "title": "NVDA",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "target": "SELECT stock, utc_timestamp, curr_price\nFROM stock.stock_table\nWHERE stock = 'NVDA'\nORDER BY utc_timestamp ASC;"
    }
   ]
  },
  {
   "title": "Streaming news",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "select news, subreddit, created_utc as time, title from stock.reddit_news"
    }
   ]
  },
  {
   "title": "AMD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "SELECT stock, utc_timestamp, curr_price\nFROM stock.stock_table\nWHERE stock = 'AMD'\nORDER BY utc_timestamp ASC;"
    }
   ]
  },
  {
   "title": "TSLA",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "target": "SELECT stock, utc_timestamp, curr_price\nFROM stock.stock_table\nWHERE stock = 'TSLA'\nORDER BY utc_timestamp ASC;"
    }
   ]
  },
  {
   "title": "AMZN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "target": "SELECT stock, utc_timestamp, curr_price\nFROM stock.stock_table\nWHERE stock = 'AMZN'\nORDER BY utc_timestamp ASC;"
    }
   ]
  },
  {
   "title": "SPY stock prediction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "target": "select stock, utc_timestamp, curr_price, predict_price\nfrom stock.predict_table\nwhere stock = 'SPY'\norder by utc_timestamp asc"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "target": "select stock, utc_timestamp, volume_cumulative from stock.stock_table;"
    }
   ]
  }
 ]
}